-- ============================================================
-- Product brand (النوع) and category (الصنف) master lists
-- Run once in: Supabase Dashboard → SQL Editor
-- Safe to re-run.
-- ============================================================

-- Product columns (if not already added)
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;

CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);

CREATE TABLE IF NOT EXISTS product_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Seed from existing product values
INSERT INTO product_brands (name)
SELECT DISTINCT TRIM(brand)
FROM products
WHERE brand IS NOT NULL AND TRIM(brand) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO product_categories (name)
SELECT DISTINCT TRIM(category)
FROM products
WHERE category IS NOT NULL AND TRIM(category) <> ''
ON CONFLICT (name) DO NOTHING;

ALTER TABLE product_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'product_brands' AND policyname = 'Allow all product_brands'
  ) THEN
    CREATE POLICY "Allow all product_brands" ON product_brands FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'product_categories' AND policyname = 'Allow all product_categories'
  ) THEN
    CREATE POLICY "Allow all product_categories" ON product_categories FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

GRANT ALL ON product_brands TO anon, authenticated;
GRANT ALL ON product_categories TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Refresh mobile_products view
DROP VIEW IF EXISTS mobile_products;
CREATE VIEW mobile_products
WITH (security_invoker = true) AS
SELECT
    p.id,
    p.name,
    p.barcode,
    p.quantity,
    p.price,
    p.cost_price,
    p.note,
    p.brand,
    p.category,
    p.supplier,
    p.supplier_id,
    p.min_stock,
    p.image_url,
    p.last_updated,
    (p.quantity <= COALESCE(p.min_stock, 5)) AS is_low_stock,
    lower(
        COALESCE(p.name, '') || ' ' ||
        COALESCE(p.barcode, '') || ' ' ||
        COALESCE(p.note, '') || ' ' ||
        COALESCE(p.brand, '') || ' ' ||
        COALESCE(p.category, '') || ' ' ||
        COALESCE(p.supplier, '')
    ) AS search_text
FROM products p;

GRANT SELECT ON mobile_products TO anon, authenticated;
