-- ============================================================
-- Mobile trial invoices (run once in Supabase SQL Editor)
-- Isolated from desktop invoices/sales — no stock or balance impact.
-- Desktop sync does NOT include these tables.
-- ============================================================

CREATE TABLE IF NOT EXISTS mobile_trial_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id),
    customer_name TEXT,
    total_amount DOUBLE PRECISION NOT NULL,
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL,
    paid_amount DOUBLE PRECISION DEFAULT 0,
    total_profit DOUBLE PRECISION DEFAULT 0,
    payment_method TEXT DEFAULT 'trial_cash',
    notes TEXT,
    created_by BIGINT REFERENCES users(id),
    created_date TIMESTAMPTZ DEFAULT NOW(),
    sale_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mobile_trial_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES mobile_trial_invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    barcode TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_price DOUBLE PRECISION NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_date TIMESTAMPTZ DEFAULT NOW(),
    customer_id BIGINT REFERENCES customers(id),
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT
);

CREATE INDEX IF NOT EXISTS idx_mobile_trial_invoices_date ON mobile_trial_invoices(sale_date);
CREATE INDEX IF NOT EXISTS idx_mobile_trial_invoices_customer ON mobile_trial_invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_mobile_trial_sales_invoice ON mobile_trial_sales(invoice_id);

ALTER TABLE mobile_trial_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_trial_sales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_all_anon_mobile_trial_invoices" ON mobile_trial_invoices;
CREATE POLICY "allow_all_anon_mobile_trial_invoices"
  ON mobile_trial_invoices FOR ALL TO anon, authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_anon_mobile_trial_sales" ON mobile_trial_sales;
CREATE POLICY "allow_all_anon_mobile_trial_sales"
  ON mobile_trial_sales FOR ALL TO anon, authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON mobile_trial_invoices TO anon, authenticated;
GRANT ALL ON mobile_trial_sales TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

SELECT 'mobile_trial tables ready' AS status;
