-- ============================================================
-- Electrical Store — Supabase (PostgreSQL) Schema
-- Run this entire file in: Supabase Dashboard → SQL Editor → New query
-- ============================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ------------------------------------------------------------
-- TABLES (order respects foreign keys)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'cashier',
    full_name TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    note TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    balance_adjustment DOUBLE PRECISION DEFAULT 0,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    barcode TEXT UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT,
    brand TEXT,
    category TEXT,
    supplier TEXT,
    supplier_id BIGINT REFERENCES suppliers(id),
    min_stock INTEGER DEFAULT 5,
    image_url TEXT,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id),
    customer_name TEXT,
    total_amount DOUBLE PRECISION NOT NULL,
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL,
    paid_amount DOUBLE PRECISION DEFAULT 0,
    total_profit DOUBLE PRECISION DEFAULT 0,
    payment_method TEXT DEFAULT 'cash',
    notes TEXT,
    created_by BIGINT REFERENCES users(id),
    created_date TIMESTAMPTZ DEFAULT NOW(),
    sale_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id),
    barcode TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_price DOUBLE PRECISION NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_date TIMESTAMPTZ DEFAULT NOW(),
    customer_id BIGINT REFERENCES customers(id),
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    invoice_id BIGINT REFERENCES invoices(id),
    note TEXT
);

CREATE TABLE IF NOT EXISTS customer_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    amount DOUBLE PRECISION NOT NULL,
    payment_date TEXT NOT NULL,
    payment_method TEXT DEFAULT 'cash',
    cheque_number TEXT,
    notes TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS discounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    discount_type TEXT NOT NULL,
    discount_value DOUBLE PRECISION NOT NULL,
    min_amount DOUBLE PRECISION DEFAULT 0,
    valid_from TIMESTAMPTZ,
    valid_to TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    adjustment_type TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    reason TEXT,
    user_id BIGINT REFERENCES users(id),
    adjustment_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cancelled_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_sale_id BIGINT NOT NULL REFERENCES sales(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    barcode TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL,
    sale_price DOUBLE PRECISION NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    profit DOUBLE PRECISION NOT NULL,
    cancel_date TIMESTAMPTZ DEFAULT NOW(),
    cancelled_by BIGINT REFERENCES users(id),
    reason TEXT
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    expense_date TIMESTAMPTZ DEFAULT NOW(),
    payment_method TEXT DEFAULT 'نقدي',
    receipt_number TEXT,
    supplier TEXT,
    notes TEXT,
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS additional_income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    description TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    income_date TIMESTAMPTZ DEFAULT NOW(),
    payment_method TEXT DEFAULT 'نقدي',
    receipt_number TEXT,
    notes TEXT,
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS budget (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    monthly_limit DOUBLE PRECISION NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    current_spent DOUBLE PRECISION DEFAULT 0,
    notes TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(category, year, month)
);

CREATE TABLE IF NOT EXISTS store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS price_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    customer_id BIGINT REFERENCES customers(id),
    notes TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW(),
    updated_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS price_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id BIGINT NOT NULL REFERENCES price_lists(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS supplier_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT NOT NULL DEFAULT 'pdf',
    comment TEXT,
    upload_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS supplier_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id),
    invoice_number TEXT NOT NULL,
    invoice_date TEXT NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    paid_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    file_path TEXT,
    file_name TEXT,
    file_type TEXT,
    notes TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS supplier_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_invoice_id BIGINT NOT NULL REFERENCES supplier_invoices(id) ON DELETE CASCADE,
    amount DOUBLE PRECISION NOT NULL,
    payment_date TEXT NOT NULL,
    payment_method TEXT DEFAULT 'cash',
    cheque_number TEXT,
    notes TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    entity_name TEXT,
    user_id BIGINT,
    user_name TEXT,
    old_value TEXT,
    new_value TEXT,
    details TEXT,
    ip_address TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Mobile-only trial invoices (NOT synced to desktop, no stock/balance impact)
CREATE TABLE IF NOT EXISTS mobile_trial_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id),
    customer_name TEXT,
    total_amount DOUBLE PRECISION NOT NULL,
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL,
    paid_amount DOUBLE PRECISION DEFAULT 0,
    total_profit DOUBLE PRECISION DEFAULT 0,
    payment_method TEXT DEFAULT 'trial_cash',
    notes TEXT,
    created_by BIGINT REFERENCES users(id),
    created_date TIMESTAMPTZ DEFAULT NOW(),
    sale_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mobile_trial_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES mobile_trial_invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    barcode TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_price DOUBLE PRECISION NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_date TIMESTAMPTZ DEFAULT NOW(),
    customer_id BIGINT REFERENCES customers(id),
    discount_amount DOUBLE PRECISION DEFAULT 0,
    final_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT
);

-- ------------------------------------------------------------
-- INDEXES
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_barcode ON sales(barcode);
CREATE INDEX IF NOT EXISTS idx_sales_invoice ON sales(invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON sales(product_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_name ON customers(name);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(created_date);
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_sale_date ON invoices(sale_date);
CREATE INDEX IF NOT EXISTS idx_invoices_number ON invoices(invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_sale_date ON invoices(customer_id, sale_date, id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_invoice ON customer_payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_customer ON customer_payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_payments_date ON customer_payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_customer_payments_customer_date ON customer_payments(customer_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_price_list_items_list ON price_list_items(price_list_id);
CREATE INDEX IF NOT EXISTS idx_price_lists_customer ON price_lists(customer_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);
CREATE INDEX IF NOT EXISTS idx_supplier_attachments_supplier ON supplier_attachments(supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_supplier ON supplier_invoices(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_invoice ON supplier_payments(supplier_invoice_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_additional_income_date ON additional_income(income_date);
CREATE INDEX IF NOT EXISTS idx_budget_year_month ON budget(year, month);
CREATE INDEX IF NOT EXISTS idx_inventory_adj_product ON inventory_adjustments(product_id);
CREATE INDEX IF NOT EXISTS idx_cancelled_sales_date ON cancelled_sales(cancel_date);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_mobile_trial_invoices_date ON mobile_trial_invoices(sale_date);
CREATE INDEX IF NOT EXISTS idx_mobile_trial_invoices_customer ON mobile_trial_invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_mobile_trial_sales_invoice ON mobile_trial_sales(invoice_id);

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY
-- Desktop store app uses the anon key with custom (local) login.
-- These policies allow full CRUD for the anon role.
-- IMPORTANT: Do not publish your anon key publicly.
-- Restrict by IP in Supabase Dashboard → Settings → API if possible.
-- ------------------------------------------------------------

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE cancelled_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE additional_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_trial_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_trial_sales ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users','suppliers','customers','product_brands','product_categories','products','invoices','sales',
    'customer_payments','discounts','inventory_adjustments','cancelled_sales',
    'expenses','additional_income','budget','store_settings','price_lists',
    'price_list_items','supplier_attachments','supplier_invoices',
    'supplier_payments','audit_logs','mobile_trial_invoices','mobile_trial_sales'
  ]
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "allow_all_anon_%s" ON %I', t, t);
    EXECUTE format(
      'CREATE POLICY "allow_all_anon_%s" ON %I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true)',
      t, t
    );
  END LOOP;
END $$;

-- Grant access
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ------------------------------------------------------------
-- MOBILE READ PERFORMANCE
-- Search indexes and read-only views live in mobile_performance.sql
-- so they can be re-applied without touching the tables above.
-- ------------------------------------------------------------

-- Done
SELECT 'Electrical Store schema created successfully' AS status;
