import 'package:flutter/material.dart';

/// Localization service for multi-language support
class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  Locale _locale = const Locale('ar');
  
  /// ILS currency symbol (Israeli New Shekel)
  static const String currencySymbol = '₪';
  
  Locale get locale => _locale;
  String get currentLanguage => _locale.languageCode;
  bool get isArabic => _locale.languageCode == 'ar';
  TextDirection get textDirection => isArabic ? TextDirection.rtl : TextDirection.ltr;

  /// Format amount with ILS currency symbol
  String formatCurrency(double amount) {
    return '$currencySymbol${amount.toStringAsFixed(2)}';
  }

  void setLocale(Locale locale) {
    _locale = locale;
    notifyListeners();
  }

  void toggleLanguage() {
    _locale = isArabic ? const Locale('en') : const Locale('ar');
    notifyListeners();
  }

  String get(String key) {
    return isArabic ? (_arStrings[key] ?? _enStrings[key] ?? key) : (_enStrings[key] ?? key);
  }

  // English strings
  static const Map<String, String> _enStrings = {
    // App Info
    'appName': 'Electrical Store',
    
    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'username': 'Username',
    'password': 'Password',
    'loginError': 'Invalid username or password',
    'welcomeBack': 'Welcome Back',
    'signIn': 'Sign In',
    'enterCredentials': 'Enter your credentials to continue',
    'pleaseEnterUsername': 'Please enter username',
    'pleaseEnterPassword': 'Please enter password',
    
    // Navigation
    'dashboard': 'Dashboard',
    'products': 'Products',
    'sales': 'Sales',
    'customers': 'Customers',
    'invoices': 'Invoices',
    'reports': 'Reports',
    'expenses': 'Expenses',
    'settings': 'Settings',
    'backup': 'Backup',
    'purchases': 'Purchases',
    
    // Dashboard
    'monthlySales': 'Monthly Sales',
    'monthlyProfit': 'Monthly Profit',
    'totalProducts': 'Total Products',
    'lowStockItems': 'Low Stock Items',
    'totalCustomers': 'Total Customers',
    'inventoryValue': 'Inventory Value',
    'totalCostValue': 'Total cost value of all products in stock',
    'quickTips': 'Quick Tips',
    'tip1': 'Review low stock items regularly',
    'tip2': 'Follow up on customer debts',
    'tip3': 'Create regular backups',
    'retry': 'Retry',
    'quickAccess': 'Quick Access',
    'quickActions': 'Quick Actions',
    'alerts': 'Alerts',
    'todaySummary': 'Today\'s Summary',
    'todaySales': 'Today\'s Sales',
    'todayProfit': 'Today\'s Profit',
    'todayInvoices': 'Today\'s Invoices',
    'manageInventory': 'Manage Inventory',
    'customerManagement': 'Customer Management',
    'viewReports': 'View Reports',
    'trackExpenses': 'Track Expenses',
    'backupData': 'Backup Data',
    'systemSettings': 'System Settings',
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    
    // Products
    'addProduct': 'Add Product',
    'editProduct': 'Edit Product',
    'deleteProduct': 'Delete Product',
    'productName': 'Product Name',
    'barcode': 'Barcode',
    'price': 'Selling Price',
    'costPrice': 'Cost Price',
    'quantity': 'Quantity',
    'category': 'Category',
    'supplier': 'Supplier',
    'minStock': 'Minimum Stock',
    'lowStock': 'Low Stock Alert',
    'outOfStock': 'Out of Stock',
    'productNotFound': 'Product not found for this barcode',
    'productOutOfStock': 'Product found but out of stock',
    'loadMore': 'Load More',
    'inStock': 'In Stock',
    'stockAdjustment': 'Stock Adjustment',
    'adjustStock': 'Adjust Stock',
    'searchProducts': 'Search products...',
    'allCategories': 'All Categories',
    'name': 'Name',
    'status': 'Status',
    'noProductsFound': 'No products found',
    'productCreated': 'Product created successfully',
    'productUpdated': 'Product updated successfully',
    'productDeleted': 'Product deleted successfully',
    'stockAdjusted': 'Stock adjusted successfully',
    'productNameRequired': 'Product name is required',
    'priceRequired': 'Price is required',
    'invalidPrice': 'Invalid price',
    'costPriceRequired': 'Cost price is required',
    'profitMargin': 'Profit Margin:',
    'adjustmentType': 'Adjustment Type',
    'stockIn': 'Stock In',
    'stockOut': 'Stock Out',
    'return': 'Return',
    'quantityRequired': 'Quantity is required',
    'cannotRemoveMoreThanStock': 'Cannot remove more than current stock',
    'reasonOptional': 'Reason (optional)',
    
    // Sales
    'newSale': 'New Sale',
    'addToCart': 'Add to Cart',
    'checkout': 'Checkout',
    'cart': 'Cart',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'grandTotal': 'Grand Total',
    'paymentMethod': 'Payment Method',
    'paymentType': 'Payment Type',
    'fullPayment': 'Full Payment',
    'partialPayment': 'Partial Payment',
    'paidAmount': 'Paid Amount',
    'remaining': 'Remaining',
    'paid': 'Paid',
    'partial': 'Partial',
    'unpaid': 'Unpaid',
    'paymentRecorded': 'Payment recorded successfully',
    'recordPayment': 'Record Payment',
    'paymentAmount': 'Payment Amount',
    'totalAmount': 'Total Amount',
    'remainingAmount': 'Remaining Amount',
    'enterPaymentAmount': 'Enter payment amount',
    'payFull': 'Pay Full',
    'cash': 'Cash',
    'card': 'Card',
    'credit': 'Credit',
    'saleCompleted': 'Sale Completed',
    'cartEmpty': 'Cart is empty',
    'editPrice': 'Edit Price',
    'customPrice': 'Custom Price',
    'originalPrice': 'Original Price',
    'newPrice': 'New Price',
    'resetPrice': 'Reset',
    'updatePrice': 'Update',
    'searchProductsOrScan': 'Search products or scan barcode...',
    'qty': 'Qty',
    'completeSale': 'Complete Sale',
    'customerOptional': 'Customer (optional)',
    'selectCustomerForCredit': 'Please select a customer for credit sales',
    'discountAmount': 'Discount Amount',
    'saleCompletedInvoice': 'Sale completed! Invoice:',
    'addCustomProduct': 'Add Custom Product',
    'customProduct': 'Custom Product',
    'enterProductName': 'Enter product name',
    'enterPrice': 'Enter price',
    'enterQuantity': 'Enter quantity',
    'addToCartCustom': 'Add to Cart',
    'validNameRequired': 'Please enter a valid name',
    'validPriceRequired': 'Please enter a valid price',
    'validQuantityRequired': 'Please enter a valid quantity',
    
    // Customers
    'addCustomer': 'Add Customer',
    'editCustomer': 'Edit Customer',
    'customerName': 'Customer Name',
    'phone': 'Phone',
    'email': 'Email',
    'address': 'Address',
    'balance': 'Balance',
    'accountStatement': 'Account Statement',
    'customerProfile': 'Customer Profile',
    'debt': 'Debt',
    'totalPurchases': 'Total Purchases',
    'newInvoice': 'New Invoice',
    'searchCustomers': 'Search customers...',
    'withDebt': 'With Debt',
    'noCustomersFound': 'No customers found',
    'customerCreated': 'Customer created successfully',
    'customerUpdated': 'Customer updated successfully',
    'customerDeleted': 'Customer deleted successfully',
    'customerNotFound': 'Customer not found',
    'nameRequired': 'Name is required',
    'validEmail': 'Please enter a valid email',
    'balanceHint': 'Positive = customer owes, Negative = store owes',
    'validNumber': 'Please enter a valid number',
    'goToSalesTab': 'Go to Sales tab to create invoice for',
    'ok': 'OK',
    'totalInvoices': 'Total Invoices',
    'noInvoicesFound': 'No invoices found',
    'createFirstInvoice': 'Create the first invoice for this customer',
    'expandAll': 'Expand All',
    'collapseAll': 'Collapse All',
    'totalDebt': 'Total Debt',
    'totalPaid': 'Total Paid',
    'paidInvoices': 'Paid Invoices',
    'unpaidInvoices': 'Unpaid Invoices',
    'confirmDeleteInvoice': 'Are you sure you want to delete invoice',
    
    // Invoices
    'invoiceNumber': 'Invoice Number',
    'searchInvoiceOrCustomer': 'Search by invoice # or customer',
    'printInvoice': 'Print Invoice',
    'exportPdf': 'Export PDF',
    'noInvoicesToExport': 'No invoices to export',
    'pdfSavedTo': 'PDF saved to',
    'customerStatement': 'Customer Statement',
    'savePdf': 'Save PDF',
    'invoiceDate': 'Invoice Date',
    'items': 'Items',
    'viewDetails': 'View Details',
    'deleteInvoice': 'Delete Invoice',
    'invoiceDeleted': 'Invoice deleted successfully',
    'pdfSaved': 'PDF saved successfully',
    'openFolder': 'Open Folder',
    'billTo': 'Bill To',
    'cashier': 'Cashier',
    'walkInCustomer': 'Walk-in Customer',
    'searchOrSelectCustomer': 'Search or select customer...',
    'thankYou': 'Thank you for your business!',
    'selectDateRange': 'Select Date Range',
    'allPaymentMethods': 'All Payment Methods',
    'showAllInvoices': 'Show All',
    'noInvoicesForPeriod': 'No invoices found for the selected period',
    'loadingItems': 'Loading items...',
    'print': 'Print',
    'invoiceNotFound': 'Invoice not found',
    'invoiceSentToPrinter': 'Invoice sent to printer',
    'invoiceSavedTo': 'Invoice saved to:',
    'unknown': 'Unknown',
    'product': 'Product',
    
    // Reports
    'dailySales': 'Daily Sales',
    'profitReport': 'Profit Report',
    'inventoryReport': 'Inventory Report',
    'customerDebts': 'Customer Debts',
    'bestSelling': 'Best Selling Products',
    'salesReport': 'Sales Report',
    'monthlySalesTab': 'Monthly Sales',
    'profit': 'Profit',
    'revenue': 'Revenue',
    'cost': 'Cost',
    'dailySalesSummary': 'Daily Sales Summary',
    'monthlySalesTrend': 'Monthly Sales Trend',
    'noSalesData': 'No sales data available for the selected period',
    'totalSales': 'Total Sales',
    'totalCost': 'Total Cost',
    'grossProfit': 'Gross Profit',
    'totalExpenses': 'Total Expenses',
    'netProfit': 'Net Profit',
    'profitMarginPercent': 'Profit Margin',
    'revenueBreakdown': 'Revenue Breakdown',
    'allProductsWellStocked': 'All products are well stocked!',
    'currentStock': 'Current Stock',
    'salesByCategory': 'Sales by Category',
    'totalCustomerDebt': 'Total Customer Debt',
    'customersWithBalance': 'Customers with Outstanding Balance',
    'noCustomersWithBalance': 'No customers with outstanding balance',
    'quantitySold': 'Quantity Sold',
    'noSalesDataAvailable': 'No sales data available',
    'inventory': 'Inventory',
    
    // Expenses
    'addExpense': 'Add Expense',
    'editExpense': 'Edit Expense',
    'expenseCategory': 'Expense Category',
    'rent': 'Rent',
    'utilities': 'Utilities',
    'salaries': 'Salaries',
    'maintenance': 'Maintenance',
    'supplies': 'Supplies',
    'shipping': 'Shipping',
    'other': 'Other',
    'noExpensesFound': 'No expenses found for the selected period',
    'expenseCreated': 'Expense created successfully',
    'expenseUpdated': 'Expense updated successfully',
    'expenseDeleted': 'Expense deleted successfully',
    'dateRequired': 'Date *',
    'categoryRequired': 'Category *',
    'selectCategory': 'Please select a category',
    'amountRequired': 'Amount *',
    'amountIsRequired': 'Amount is required',
    'validAmount': 'Please enter a valid amount',
    'confirmDeleteExpense': 'Are you sure you want to delete this expense?',
    
    // Settings
    'storeName': 'Store Name',
    'storeSettings': 'Store Settings',
    'currency': 'Currency',
    'language': 'Language',
    'select_language': 'Select Language',
    'arabic': 'Arabic',
    'english': 'English',
    'taxRate': 'Tax Rate',
    'saveSettings': 'Save Settings',
    'storeInformation': 'Store Information',
    'storeNameRequired': 'Store name is required',
    'contactInformation': 'Contact Information',
    'financialSettings': 'Financial Settings',
    'taxRatePercent': 'Tax Rate (%)',
    'taxRateRange': 'Tax rate must be between 0 and 100',
    'currencyRequired': 'Currency is required',
    'languageApplied': 'Language will be applied throughout the app',
    'systemInformation': 'System Information',
    'appVersion': 'Application Version',
    'database': 'Database',
    'platform': 'Platform',
    'desktop': 'Desktop',
    'settingsSaved': 'Settings saved successfully',
    'errorLoadingSettings': 'Error loading settings:',
    'errorSavingSettings': 'Error saving settings:',
    
    // Backup
    'createBackup': 'Create Backup',
    'restoreBackup': 'Restore Backup',
    'backupHistory': 'Backup History',
    'lastBackup': 'Last Backup',
    'autoBackup': 'Auto Backup',
    'createBackupDesc': 'Create a new backup of all your data',
    'restoreFromFile': 'Restore from File',
    'selectBackupFile': 'Select a backup file to restore',
    'browseFiles': 'Browse Files',
    'selectBackupHint': 'Select a backup from the list below or manually browse to the backup directory',
    'noBackupsFound': 'No backups found',
    'createFirstBackup': 'Create your first backup to protect your data',
    'restore': 'Restore',
    'confirmRestore': 'Confirm Restore',
    'restoreWarning': 'This will replace all current data with the backup. This action cannot be undone. Are you sure?',
    'backupCreated': 'Backup created successfully at:',
    'backupFailed': 'Backup failed:',
    'backupRestored': 'Backup restored successfully. Please restart the application.',
    'restoreFailed': 'Restore failed:',
    'confirmDeleteBackup': 'Are you sure you want to delete this backup?',
    'backupDeleted': 'Backup deleted',
    'deleteFailed': 'Delete failed:',
    'backupTips': 'Backup Tips',
    
    // Common
    'save': 'Save',
    'record': 'Record',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'search': 'Search',
    'filter': 'Filter',
    'refresh': 'Refresh',
    'loading': 'Loading...',
    'noData': 'No data available',
    'success': 'Success',
    'error': 'Error',
    'confirm': 'Confirm',
    'confirmDelete': 'Are you sure you want to delete?',
    'confirmDeleteItem': 'Are you sure you want to delete',
    'yes': 'Yes',
    'no': 'No',
    'date': 'Date',
    'amount': 'Amount',
    'description': 'Description',
    'notes': 'Notes',
    'enterNotes': 'Enter notes...',
    'noNotes': 'No notes',
    'notesSaved': 'Notes saved',
    'actions': 'Actions',
    'close': 'Close',
    'details': 'Details',
    'all': 'All',
    'today': 'Today',
    'thisWeek': 'This Week',
    'thisMonth': 'This Month',
    'selectDate': 'Select Date',
    'from': 'From',
    'to': 'To',
    'clear': 'Clear',
    'apply': 'Apply',
    'reset': 'Reset',
    'update': 'Update',
    'required': 'Required',
    'optional': 'Optional',
    'notFound': 'Not Found',
    'noResults': 'No results found',
    'errorDeleting': 'Error deleting:',
    'editing': 'Editing',
    'payment': 'Payment',
    
    // Price Lists
    'priceLists': 'Price Lists',
    'createPriceList': 'Create Price List',
    'editPriceList': 'Edit Price List',
    'priceListDescription': 'Create price quotations for clients. Price lists do not affect inventory.',
    'searchPriceLists': 'Search by title or customer...',
    'noPriceListsFound': 'No price lists found',
    'priceListCreated': 'Price list created successfully',
    'priceListUpdated': 'Price list updated successfully',
    'priceListDeleted': 'Price list deleted successfully',
    'priceListNotFound': 'Price list not found',
    'noInventoryImpact': 'Does not affect inventory',
    'addProducts': 'Add Products',
    'pleaseAddItems': 'Please add at least one item',
    'titleRequired': 'Title is required',
    'noCustomer': 'No Customer',
    'title': 'Title',
    
    // User Management
    'userManagement': 'User Management',
    'addUser': 'Add User',
    'editUser': 'Edit User',
    'deleteUser': 'Delete User',
    'users': 'Users',
    'fullName': 'Full Name',
    'role': 'Role',
    'admin': 'Admin',
    'user': 'User',
    'userCreated': 'User created successfully',
    'userUpdated': 'User updated successfully',
    'userDeleted': 'User deleted successfully',
    'confirmDeleteUser': 'Are you sure you want to delete this user?',
    'cannotDeleteLastAdmin': 'Cannot delete the last admin user',
    'usernameRequired': 'Username is required',
    'passwordRequired': 'Password is required',
    'usernameExists': 'Username already exists',
    'confirmPassword': 'Confirm Password',
    'passwordsDoNotMatch': 'Passwords do not match',
    'noUsersFound': 'No users found',
    'manageUsers': 'Manage users who can access the system',
    
    // AI Chatbot
    'aiAssistant': 'AI Assistant',
    'askMeAnything': 'Ask me anything',
    'clearChat': 'Clear chat',
    'typeMessage': 'Type a message...',
    'smartSearch': 'Smart Search',
    
    // Suppliers
    'suppliers': 'Suppliers',
    'addSupplier': 'Add Supplier',
    'editSupplier': 'Edit Supplier',
    'deleteSupplier': 'Delete Supplier',
    'supplierName': 'Supplier Name',
    'supplierNameRequired': 'Supplier name is required',
    'searchSuppliers': 'Search by name, phone, or address...',
    'noSuppliersFound': 'No suppliers found',
    'supplierCreated': 'Supplier created successfully',
    'supplierUpdated': 'Supplier updated successfully',
    'supplierDeleted': 'Supplier deleted successfully',
    'confirmDeleteSupplier': 'Are you sure you want to delete this supplier? All attachments will be removed.',
    'attachments': 'Attachments',
    'uploadFile': 'Upload File',
    'selectFile': 'Select File',
    'addComment': 'Add Comment',
    'editComment': 'Edit Comment',
    'optionalComment': 'Optional comment...',
    'skip': 'Skip',
    'noAttachments': 'No attachments yet',
    'openFile': 'Open File',
    'fileNotFound': 'File not found',
    'attachmentAdded': 'Attachment added successfully',
    'attachmentDeleted': 'Attachment deleted successfully',
    'confirmDeleteAttachment': 'Are you sure you want to delete this attachment?',
    'selectSupplier': 'Select Supplier',
    'noSupplier': 'No Supplier',
  };

  // Arabic strings
  static const Map<String, String> _arStrings = {
    // App Info
    'appName': 'متجر الأدوات الكهربائية',
    
    // Auth
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'loginError': 'اسم المستخدم أو كلمة المرور غير صحيحة',
    'welcomeBack': 'مرحباً بعودتك',
    'signIn': 'دخول',
    'enterCredentials': 'أدخل بيانات الاعتماد للمتابعة',
    'pleaseEnterUsername': 'يرجى إدخال اسم المستخدم',
    'pleaseEnterPassword': 'يرجى إدخال كلمة المرور',
    
    // Navigation
    'dashboard': 'لوحة التحكم',
    'products': 'المنتجات',
    'sales': 'المبيعات',
    'customers': 'العملاء',
    'invoices': 'الفواتير',
    'reports': 'التقارير',
    'expenses': 'المصروفات',
    'settings': 'الإعدادات',
    'backup': 'النسخ الاحتياطي',
    'purchases': 'المشتريات',
    
    // Dashboard
    'monthlySales': 'المبيعات الشهرية',
    'monthlyProfit': 'الربح الشهري',
    'totalProducts': 'إجمالي المنتجات',
    'lowStockItems': 'منتجات قليلة المخزون',
    'totalCustomers': 'إجمالي العملاء',
    'inventoryValue': 'قيمة المخزون',
    'totalCostValue': 'إجمالي قيمة تكلفة جميع المنتجات في المخزون',
    'quickTips': 'نصائح سريعة',
    'tip1': 'راجع المنتجات قليلة المخزون بانتظام',
    'tip2': 'تابع ديون العملاء',
    'tip3': 'أنشئ نسخ احتياطية بانتظام',
    'retry': 'إعادة المحاولة',
    'quickAccess': 'الوصول السريع',
    'quickActions': 'إجراءات سريعة',
    'alerts': 'التنبيهات',
    'todaySummary': 'ملخص اليوم',
    'todaySales': 'مبيعات اليوم',
    'todayProfit': 'ربح اليوم',
    'todayInvoices': 'فواتير اليوم',
    'manageInventory': 'إدارة المخزون',
    'customerManagement': 'إدارة العملاء',
    'viewReports': 'عرض التقارير',
    'trackExpenses': 'تتبع المصروفات',
    'backupData': 'نسخ البيانات',
    'systemSettings': 'إعدادات النظام',
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    
    // Products
    'addProduct': 'إضافة منتج',
    'editProduct': 'تعديل منتج',
    'deleteProduct': 'حذف منتج',
    'productName': 'اسم المنتج',
    'barcode': 'الباركود',
    'price': 'سعر البيع',
    'costPrice': 'سعر التكلفة',
    'quantity': 'الكمية',
    'category': 'الفئة',
    'supplier': 'المورد',
    'minStock': 'الحد الأدنى للمخزون',
    'lowStock': 'تنبيه انخفاض المخزون',
    'outOfStock': 'نفد من المخزون',
    'productNotFound': 'المنتج غير موجود لهذا الباركود',
    'productOutOfStock': 'المنتج موجود لكنه نفد من المخزون',
    'loadMore': 'تحميل المزيد',
    'inStock': 'متوفر',
    'stockAdjustment': 'تعديل المخزون',
    'adjustStock': 'ضبط المخزون',
    'searchProducts': 'بحث عن المنتجات...',
    'allCategories': 'جميع الفئات',
    'name': 'الاسم',
    'status': 'الحالة',
    'noProductsFound': 'لا توجد منتجات',
    'productCreated': 'تم إنشاء المنتج بنجاح',
    'productUpdated': 'تم تحديث المنتج بنجاح',
    'productDeleted': 'تم حذف المنتج بنجاح',
    'stockAdjusted': 'تم تعديل المخزون بنجاح',
    'productNameRequired': 'اسم المنتج مطلوب',
    'priceRequired': 'السعر مطلوب',
    'invalidPrice': 'سعر غير صالح',
    'costPriceRequired': 'سعر التكلفة مطلوب',
    'profitMargin': 'هامش الربح:',
    'adjustmentType': 'نوع التعديل',
    'stockIn': 'إدخال مخزون',
    'stockOut': 'إخراج مخزون',
    'return': 'مرتجع',
    'quantityRequired': 'الكمية مطلوبة',
    'cannotRemoveMoreThanStock': 'لا يمكن إزالة أكثر من المخزون الحالي',
    'reasonOptional': 'السبب (اختياري)',
    
    // Sales
    'newSale': 'بيع جديد',
    'addToCart': 'إضافة للسلة',
    'checkout': 'إتمام الشراء',
    'cart': 'السلة',
    'total': 'الإجمالي',
    'subtotal': 'المجموع الفرعي',
    'discount': 'الخصم',
    'grandTotal': 'المجموع الكلي',
    'paymentMethod': 'طريقة الدفع',
    'paymentType': 'نوع الدفع',
    'fullPayment': 'دفع كامل',
    'partialPayment': 'دفع جزئي',
    'paidAmount': 'المبلغ المدفوع',
    'remaining': 'المتبقي',
    'paid': 'مدفوع',
    'partial': 'جزئي',
    'unpaid': 'غير مدفوع',
    'paymentRecorded': 'تم تسجيل الدفعة بنجاح',
    'recordPayment': 'تسجيل دفعة',
    'paymentAmount': 'مبلغ الدفعة',
    'totalAmount': 'المبلغ الإجمالي',
    'remainingAmount': 'المبلغ المتبقي',
    'enterPaymentAmount': 'أدخل مبلغ الدفعة',
    'payFull': 'دفع كامل',
    'cash': 'نقداً',
    'card': 'بطاقة',
    'credit': 'آجل',
    'saleCompleted': 'تمت عملية البيع',
    'cartEmpty': 'السلة فارغة',
    'editPrice': 'تعديل السعر',
    'customPrice': 'سعر مخصص',
    'originalPrice': 'السعر الأصلي',
    'newPrice': 'السعر الجديد',
    'resetPrice': 'إعادة تعيين',
    'updatePrice': 'تحديث',
    'searchProductsOrScan': 'بحث عن المنتجات أو مسح الباركود...',
    'qty': 'الكمية',
    'completeSale': 'إتمام البيع',
    'customerOptional': 'العميل (اختياري)',
    'selectCustomerForCredit': 'يرجى اختيار عميل للمبيعات الآجلة',
    'discountAmount': 'مبلغ الخصم',
    'saleCompletedInvoice': 'تمت عملية البيع! رقم الفاتورة:',
    'addCustomProduct': 'إضافة منتج مخصص',
    'customProduct': 'منتج مخصص',
    'enterProductName': 'أدخل اسم المنتج',
    'enterPrice': 'أدخل السعر',
    'enterQuantity': 'أدخل الكمية',
    'addToCartCustom': 'إضافة للسلة',
    'validNameRequired': 'يرجى إدخال اسم صحيح',
    'validPriceRequired': 'يرجى إدخال سعر صحيح',
    'validQuantityRequired': 'يرجى إدخال كمية صحيحة',
    
    // Customers
    'addCustomer': 'إضافة عميل',
    'editCustomer': 'تعديل عميل',
    'customerName': 'اسم العميل',
    'phone': 'الهاتف',
    'email': 'البريد الإلكتروني',
    'address': 'العنوان',
    'balance': 'الرصيد',
    'accountStatement': 'كشف الحساب',
    'customerProfile': 'ملف العميل',
    'debt': 'الدين',
    'totalPurchases': 'إجمالي المشتريات',
    'newInvoice': 'فاتورة جديدة',
    'searchCustomers': 'بحث عن العملاء...',
    'withDebt': 'مع ديون',
    'noCustomersFound': 'لا يوجد عملاء',
    'customerCreated': 'تم إنشاء العميل بنجاح',
    'customerUpdated': 'تم تحديث العميل بنجاح',
    'customerDeleted': 'تم حذف العميل بنجاح',
    'customerNotFound': 'العميل غير موجود',
    'nameRequired': 'الاسم مطلوب',
    'validEmail': 'يرجى إدخال بريد إلكتروني صالح',
    'balanceHint': 'موجب = العميل مدين، سالب = المتجر مدين',
    'expandAll': 'توسيع الكل',
    'collapseAll': 'طي الكل',
    'totalDebt': 'إجمالي الدين',
    'totalPaid': 'إجمالي المدفوع',
    'paidInvoices': 'الفواتير المدفوعة',
    'unpaidInvoices': 'الفواتير غير المدفوعة',
    'confirmDeleteInvoice': 'هل أنت متأكد من حذف الفاتورة',
    'validNumber': 'يرجى إدخال رقم صالح',
    'goToSalesTab': 'اذهب إلى تبويب المبيعات لإنشاء فاتورة لـ',
    'ok': 'موافق',
    'totalInvoices': 'إجمالي الفواتير',
    'noInvoicesFound': 'لا توجد فواتير',
    'createFirstInvoice': 'أنشئ أول فاتورة لهذا العميل',
    
    // Invoices
    'invoiceNumber': 'رقم الفاتورة',
    'searchInvoiceOrCustomer': 'بحث برقم الفاتورة أو اسم العميل',
    'printInvoice': 'طباعة الفاتورة',
    'exportPdf': 'تصدير PDF',
    'noInvoicesToExport': 'لا توجد فواتير للتصدير',
    'pdfSavedTo': 'تم حفظ PDF في',
    'customerStatement': 'كشف حساب العميل',
    'savePdf': 'حفظ PDF',
    'invoiceDate': 'تاريخ الفاتورة',
    'items': 'العناصر',
    'viewDetails': 'عرض التفاصيل',
    'deleteInvoice': 'حذف الفاتورة',
    'invoiceDeleted': 'تم حذف الفاتورة بنجاح',
    'pdfSaved': 'تم حفظ ملف PDF بنجاح',
    'openFolder': 'فتح المجلد',
    'billTo': 'الفاتورة إلى',
    'cashier': 'الكاشير',
    'walkInCustomer': 'عميل عابر',
    'searchOrSelectCustomer': 'ابحث أو اختر عميل...',
    'thankYou': 'شكراً لتعاملكم معنا!',
    'selectDateRange': 'اختر نطاق التاريخ',
    'allPaymentMethods': 'جميع طرق الدفع',
    'showAllInvoices': 'عرض الكل',
    'noInvoicesForPeriod': 'لا توجد فواتير للفترة المحددة',
    'loadingItems': 'جاري تحميل العناصر...',
    'print': 'طباعة',
    'invoiceNotFound': 'الفاتورة غير موجودة',
    'invoiceSentToPrinter': 'تم إرسال الفاتورة للطابعة',
    'invoiceSavedTo': 'تم حفظ الفاتورة في:',
    'unknown': 'غير معروف',
    'product': 'المنتج',
    
    // Reports
    'dailySales': 'المبيعات اليومية',
    'profitReport': 'تقرير الأرباح',
    'inventoryReport': 'تقرير المخزون',
    'customerDebts': 'ديون العملاء',
    'bestSelling': 'الأكثر مبيعاً',
    'salesReport': 'تقرير المبيعات',
    'monthlySalesTab': 'المبيعات الشهرية',
    'profit': 'الربح',
    'revenue': 'الإيرادات',
    'cost': 'التكلفة',
    'dailySalesSummary': 'ملخص المبيعات اليومية',
    'monthlySalesTrend': 'اتجاه المبيعات الشهرية',
    'noSalesData': 'لا توجد بيانات مبيعات للفترة المحددة',
    'totalSales': 'إجمالي المبيعات',
    'totalCost': 'إجمالي التكلفة',
    'grossProfit': 'الربح الإجمالي',
    'totalExpenses': 'إجمالي المصروفات',
    'netProfit': 'صافي الربح',
    'profitMarginPercent': 'هامش الربح',
    'revenueBreakdown': 'تفصيل الإيرادات',
    'allProductsWellStocked': 'جميع المنتجات متوفرة بشكل جيد!',
    'currentStock': 'المخزون الحالي',
    'salesByCategory': 'المبيعات حسب الفئة',
    'totalCustomerDebt': 'إجمالي ديون العملاء',
    'customersWithBalance': 'العملاء ذوو الرصيد المستحق',
    'noCustomersWithBalance': 'لا يوجد عملاء برصيد مستحق',
    'quantitySold': 'الكمية المباعة',
    'noSalesDataAvailable': 'لا توجد بيانات مبيعات',
    'inventory': 'المخزون',
    
    // Expenses
    'addExpense': 'إضافة مصروف',
    'editExpense': 'تعديل مصروف',
    'expenseCategory': 'فئة المصروفات',
    'rent': 'الإيجار',
    'utilities': 'المرافق',
    'salaries': 'الرواتب',
    'maintenance': 'الصيانة',
    'supplies': 'اللوازم',
    'shipping': 'الشحن',
    'other': 'أخرى',
    'noExpensesFound': 'لا توجد مصروفات للفترة المحددة',
    'expenseCreated': 'تم إنشاء المصروف بنجاح',
    'expenseUpdated': 'تم تحديث المصروف بنجاح',
    'expenseDeleted': 'تم حذف المصروف بنجاح',
    'dateRequired': 'التاريخ *',
    'categoryRequired': 'الفئة *',
    'selectCategory': 'يرجى اختيار فئة',
    'amountRequired': 'المبلغ *',
    'amountIsRequired': 'المبلغ مطلوب',
    'validAmount': 'يرجى إدخال مبلغ صالح',
    'confirmDeleteExpense': 'هل أنت متأكد من حذف هذا المصروف؟',
    
    // Settings
    'storeName': 'اسم المتجر',
    'storeSettings': 'إعدادات المتجر',
    'currency': 'العملة',
    'language': 'اللغة',
    'select_language': 'اختر اللغة',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    'taxRate': 'نسبة الضريبة',
    'saveSettings': 'حفظ الإعدادات',
    'storeInformation': 'معلومات المتجر',
    'storeNameRequired': 'اسم المتجر مطلوب',
    'contactInformation': 'معلومات الاتصال',
    'financialSettings': 'الإعدادات المالية',
    'taxRatePercent': 'نسبة الضريبة (%)',
    'taxRateRange': 'نسبة الضريبة يجب أن تكون بين 0 و 100',
    'currencyRequired': 'العملة مطلوبة',
    'languageApplied': 'سيتم تطبيق اللغة على كل التطبيق',
    'systemInformation': 'معلومات النظام',
    'appVersion': 'إصدار التطبيق',
    'database': 'قاعدة البيانات',
    'platform': 'المنصة',
    'desktop': 'سطح المكتب',
    'settingsSaved': 'تم حفظ الإعدادات بنجاح',
    'errorLoadingSettings': 'خطأ في تحميل الإعدادات:',
    'errorSavingSettings': 'خطأ في حفظ الإعدادات:',
    
    // Backup
    'createBackup': 'إنشاء نسخة احتياطية',
    'restoreBackup': 'استعادة نسخة احتياطية',
    'backupHistory': 'سجل النسخ الاحتياطية',
    'lastBackup': 'آخر نسخة احتياطية',
    'autoBackup': 'نسخ احتياطي تلقائي',
    'createBackupDesc': 'إنشاء نسخة احتياطية جديدة لجميع بياناتك',
    'restoreFromFile': 'استعادة من ملف',
    'selectBackupFile': 'اختر ملف نسخة احتياطية للاستعادة',
    'browseFiles': 'تصفح الملفات',
    'selectBackupHint': 'اختر نسخة احتياطية من القائمة أدناه أو تصفح يدوياً إلى مجلد النسخ الاحتياطية',
    'noBackupsFound': 'لا توجد نسخ احتياطية',
    'createFirstBackup': 'أنشئ أول نسخة احتياطية لحماية بياناتك',
    'restore': 'استعادة',
    'confirmRestore': 'تأكيد الاستعادة',
    'restoreWarning': 'سيؤدي هذا إلى استبدال جميع البيانات الحالية بالنسخة الاحتياطية. لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد؟',
    'backupCreated': 'تم إنشاء النسخة الاحتياطية بنجاح في:',
    'backupFailed': 'فشل النسخ الاحتياطي:',
    'backupRestored': 'تم استعادة النسخة الاحتياطية بنجاح. يرجى إعادة تشغيل التطبيق.',
    'restoreFailed': 'فشل الاستعادة:',
    'confirmDeleteBackup': 'هل أنت متأكد من حذف هذه النسخة الاحتياطية؟',
    'backupDeleted': 'تم حذف النسخة الاحتياطية',
    'deleteFailed': 'فشل الحذف:',
    'backupTips': 'نصائح النسخ الاحتياطي',
    
    // Common
    'save': 'حفظ',
    'record': 'تسجيل',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'search': 'بحث',
    'filter': 'تصفية',
    'refresh': 'تحديث',
    'loading': 'جاري التحميل...',
    'noData': 'لا توجد بيانات',
    'success': 'نجاح',
    'error': 'خطأ',
    'confirm': 'تأكيد',
    'confirmDelete': 'هل أنت متأكد من الحذف؟',
    'confirmDeleteItem': 'هل أنت متأكد من حذف',
    'yes': 'نعم',
    'no': 'لا',
    'date': 'التاريخ',
    'amount': 'المبلغ',
    'description': 'الوصف',
    'notes': 'ملاحظات',
    'enterNotes': 'أدخل ملاحظات...',
    'noNotes': 'لا توجد ملاحظات',
    'notesSaved': 'تم حفظ الملاحظات',
    'actions': 'الإجراءات',
    'close': 'إغلاق',
    'details': 'التفاصيل',
    'all': 'الكل',
    'today': 'اليوم',
    'thisWeek': 'هذا الأسبوع',
    'thisMonth': 'هذا الشهر',
    'selectDate': 'اختر التاريخ',
    'from': 'من',
    'to': 'إلى',
    'clear': 'مسح',
    'apply': 'تطبيق',
    'reset': 'إعادة تعيين',
    'update': 'تحديث',
    'required': 'مطلوب',
    'optional': 'اختياري',
    'notFound': 'غير موجود',
    'noResults': 'لا توجد نتائج',
    'errorDeleting': 'خطأ في الحذف:',
    'editing': 'تعديل',
    'payment': 'الدفع',
    
    // Price Lists
    'priceLists': 'قوائم الأسعار',
    'createPriceList': 'إنشاء قائمة أسعار',
    'editPriceList': 'تعديل قائمة أسعار',
    'priceListDescription': 'إنشاء عروض أسعار للعملاء. قوائم الأسعار لا تؤثر على المخزون.',
    'searchPriceLists': 'بحث بالعنوان أو اسم العميل...',
    'noPriceListsFound': 'لا توجد قوائم أسعار',
    'priceListCreated': 'تم إنشاء قائمة الأسعار بنجاح',
    'priceListUpdated': 'تم تحديث قائمة الأسعار بنجاح',
    'priceListDeleted': 'تم حذف قائمة الأسعار بنجاح',
    'priceListNotFound': 'قائمة الأسعار غير موجودة',
    'noInventoryImpact': 'لا تؤثر على المخزون',
    'addProducts': 'إضافة منتجات',
    'pleaseAddItems': 'يرجى إضافة عنصر واحد على الأقل',
    'titleRequired': 'العنوان مطلوب',
    'noCustomer': 'بدون عميل',
    'title': 'العنوان',
    
    // User Management
    'userManagement': 'إدارة المستخدمين',
    'addUser': 'إضافة مستخدم',
    'editUser': 'تعديل مستخدم',
    'deleteUser': 'حذف مستخدم',
    'users': 'المستخدمون',
    'fullName': 'الاسم الكامل',
    'role': 'الدور',
    'admin': 'مسؤول',
    'user': 'مستخدم',
    'userCreated': 'تم إنشاء المستخدم بنجاح',
    'userUpdated': 'تم تحديث المستخدم بنجاح',
    'userDeleted': 'تم حذف المستخدم بنجاح',
    'confirmDeleteUser': 'هل أنت متأكد من حذف هذا المستخدم؟',
    'cannotDeleteLastAdmin': 'لا يمكن حذف آخر مستخدم مسؤول',
    'usernameRequired': 'اسم المستخدم مطلوب',
    'passwordRequired': 'كلمة المرور مطلوبة',
    'usernameExists': 'اسم المستخدم موجود مسبقاً',
    'confirmPassword': 'تأكيد كلمة المرور',
    'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
    'noUsersFound': 'لا يوجد مستخدمون',
    'manageUsers': 'إدارة المستخدمين الذين يمكنهم الوصول إلى النظام',
    
    // AI Chatbot
    'aiAssistant': 'المساعد الذكي',
    'askMeAnything': 'اسألني أي شيء',
    'clearChat': 'مسح المحادثة',
    'typeMessage': 'اكتب رسالة...',
    'smartSearch': 'البحث الذكي',
    
    // Suppliers
    'suppliers': 'الموردون',
    'addSupplier': 'إضافة مورد',
    'editSupplier': 'تعديل مورد',
    'deleteSupplier': 'حذف مورد',
    'supplierName': 'اسم المورد',
    'supplierNameRequired': 'اسم المورد مطلوب',
    'searchSuppliers': 'بحث بالاسم أو الهاتف أو العنوان...',
    'noSuppliersFound': 'لا يوجد موردون',
    'supplierCreated': 'تم إنشاء المورد بنجاح',
    'supplierUpdated': 'تم تحديث المورد بنجاح',
    'supplierDeleted': 'تم حذف المورد بنجاح',
    'confirmDeleteSupplier': 'هل أنت متأكد من حذف هذا المورد؟ سيتم حذف جميع المرفقات.',
    'attachments': 'المرفقات',
    'uploadFile': 'رفع ملف',
    'selectFile': 'اختر ملف',
    'addComment': 'إضافة تعليق',
    'editComment': 'تعديل التعليق',
    'optionalComment': 'تعليق اختياري...',
    'skip': 'تخطي',
    'noAttachments': 'لا توجد مرفقات',
    'openFile': 'فتح الملف',
    'fileNotFound': 'الملف غير موجود',
    'attachmentAdded': 'تمت إضافة المرفق بنجاح',
    'attachmentDeleted': 'تم حذف المرفق بنجاح',
    'confirmDeleteAttachment': 'هل أنت متأكد من حذف هذا المرفق؟',
    'selectSupplier': 'اختر المورد',
    'noSupplier': 'بدون مورد',
  };
}

/// Extension for easy localization access
extension LocalizationExtension on BuildContext {
  LocalizationService get l10n => LocalizationService();
  String tr(String key) => LocalizationService().get(key);
  bool get isRtl => LocalizationService().isArabic;
  TextDirection get textDirection => LocalizationService().textDirection;
}
